### ISSUE TITLE
TypeError: (0 , validators_1.check) is not a function

### ISSUE THREAD

**Issue by rilysh** [XzFirzal/lavacoffee#5]
**Describe the problem:** I just clone lavacoffee GitHub repo and configure everything, when I trying to execute example (in test folder) found this error `(0 , validators_1.check) is not a function` from CoffeeRoutePlanner. To ensure I've also tried npm version but got different error `TypeError: Cannot read properties of undefined (reading 'value')`. Supposed descriptor is undefied.

**GitHub Version Error:**
```
/home/luha/Desktop/lavacoffee/src/structures/CoffeeRoutePlanner.js:95
        (0, validators_1.check)(function (method, address) {
                               ^

TypeError: (0 , validators_1.check) is not a function
    at /home/luha/Desktop/lavacoffee/src/structures/CoffeeRoutePlanner.js:95:32
    at Object.<anonymous> (/home/luha/Desktop/lavacoffee/src/structures/CoffeeRoutePlanner.js:102:2)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/luha/Desktop/lavacoffee/src/structures/CoffeeNode.js:78:28)
```

**npm version error:**
```
/home/luha/Desktop/lavacoffee/test/node_modules/lavacoffee/dist/utils/decorators/validators.js:7
        const method = descriptor.value;
                                  ^

TypeError: Cannot read properties of undefined (reading 'value')
    at decorate (/home/luha/Desktop/lavacoffee/test/node_modules/lavacoffee/dist/utils/decorators/validators.js:7:35)
    at __decorate (/home/luha/Desktop/lavacoffee/test/node_modules/lavacoffee/dist/structures/CoffeeRoutePlanner.js:5:130)
    at /home/luha/Desktop/lavacoffee/test/node_modules/lavacoffee/dist/structures/CoffeeRoutePlanner.js:94:5
    at Object.<anonymous> (/home/luha/Desktop/lavacoffee/test/node_modules/lavacoffee/dist/structures/CoffeeRoutePlanner.js:102:2)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

Not absolutely sure is that my problem somewhere else, since I'm pretty new in TS, can you point me out if I've done any mistake? Used lavacoffee example bot https://github.com/Azusfin/lavacoffee/blob/main/test/index.ts

Thanks!

**Comment by Azusfin** [comment]
![image](https://cdn.discordapp.com/attachments/789656208276848682/932931838664667186/aasasdggasgsdasdggsdasdggsdagasdsgasgagsdadgsasd.png)
totally fine for me 🤔

make sure the index is imported first before importing other (importing dist/utils for example)

**Comment by rilysh** [comment]
> ![image](https://camo.githubusercontent.com/e7dfeaa780d474b4387559368cb65772ce67deb82bb89a02ef5010092472b695/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3738393635363230383237363834383638322f3933323933313833383636343636373138362f6161736173646767617367736461736467677364617364676773646167617364736761736761677364616467736173642e706e67) totally fine for me thinking
> 
> make sure the index is imported first before importing other (importing dist/utils for example)

Thank you! It works fine now! :+1:
